name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python-version: 3.6, os: ubuntu-latest, toxenv: py }
          - { python-version: 3.7, os: ubuntu-latest, toxenv: py }
          - { python-version: 3.8, os: ubuntu-latest, toxenv: py }
          - { python-version: 3.8, os: ubuntu-latest, toxenv: style }
          - { python-version: 3.8, os: ubuntu-latest, toxenv: docs }
          - { python-version: 3.8, os: windows-latest, toxenv: py }
          - { python-version: 3.7, os: macos-latest, toxenv: py }

#  3.8 Linux py
#  3.7 Linux py
#  3.6 Linux py
#  3.8 Linux style
#  3.8 Linux docs
#  3.8 Windows py
#  3.7 Mac py

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get pip cache dir
        id: pip-cache
        run: |
          python -m pip install -U "pip>=20.1"
          echo "::set-output name=dir::$(pip cache dir)"

      - name: pip cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key:
            ${{ matrix.os }}-${{ matrix.python-version }}-v2-${{
            hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.python-version }}-v2-

      - name: Install dependencies
        run: |
          python -m pip install -U wheel
          python -m pip install -U tox

      - name: Test with tox ${{ matrix.toxenv }}
        shell: bash
        run: |
          tox
        env:
          TOXENV: ${{ matrix.toxenv }}

      - name: Upload coverage
        if: success()
        run: |
          curl --retry 8 -s https://codecov.io/bash -o codecov.sh
          bash codecov.sh -F ${{ matrix.codecov-flag }}
        env:
          CODECOV_NAME: ${{ matrix.os }} Python ${{ matrix.python-version }}
